#!/bin/sh
[ -z "$2" ] && num="2" || num="$2"

case "$1" in
	u*) pactl set-sink-volume 0 +5% ;;
	d*) pactl set-sink-volume 0 -5% ;;
	m*) pactl set-sink-mute 0 toggle ;;
	*) cat << EOF
EOF
esac

pkill -RTMIN+10 i3blocks
